import webizign from './Assets/Event_posters/CSE/Webizign.png'
import velocity from './Assets/Event_posters/CSE/velocity.png'
import TechWizard from './Assets/Event_posters/CSE/TechWizard .png'
import Spiderz from './Assets/Event_posters/CSE/Spiderz.png'
import SpeedFreak from './Assets/Event_posters/CSE/SpeedFreak.png'
import Playplex from './Assets/Event_posters/CSE/Playplex.png'
import Patternprinting from './Assets/Event_posters/CSE/Patternprinting .png'
import Hyperlink from './Assets/Event_posters/CSE/Hyperlink.png'
import Hackathon from './Assets/Event_posters/CSE/Hackathon.png'
import Filmtivia from './Assets/Event_posters/CSE/Filmtrivia .png'
import cyberverse from './Assets/Event_posters/CSE/cyberverse.png'
import CodeMafia from './Assets/Event_posters/CSE/CodeMafia.png'



const events = {
    cse: [
        {
            id: 1,
            title: "Velocity - Type Racer",
            first_price: "1500",
            second_price: "500",
            third_price: "",
            prizeCount: 2,
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "10:00 AM - 12:00 PM",
            desc: "Think you're the fastest typist around? Prove it! Join our speed typing event, race against the clock, and claim the title of typing master. Exciting prizes await the winner!",
            rules: [
                "He or she must type the entire passage within the allotted time.",
                "Errors will result in loss of points.",
                "Players with the highest Words Per Minute (WPM) wins the game.",
                "Decision of judge's will be final."
            ],
            reg_fees: "30",
            posterImg: velocity,
            coordinator: ["Manu V V", "Harigovind S", "Josekutty George"],
            contact_coordinator: ["8921767709", "9188358027", "8086671175"],
        },
        {
            id: 2,
            title: "SPEED FREAK - NFS GAMING",
            first_price: "1500",
            second_price: "1000",
            third_price: "500",
            prizeCount: 3,
            type: "Individual",
            mode: "Offline",
            date: "20",
            time: "9:00 AM - 2:30 PM",
            desc: "Get ready to rev your engines and put your racing skills to the test! Compete in the ultimate LAN multiplayer event of Need for Speed and battle it out against other players for the prestigious Racing King title. Do you have what it takes to be crowned the champion?",
            rules: [
                "Players need ‘Not’ bring their laptop to participate in the event.",
                "Event is conducted as two rounds: Preliminary round and Race round.",
                "The Preliminary Round is a walk-in round. The time of completing the circuit will be recorded. This time is used to shortlist the participants to the next round. Note that this will be an individual event.",
                "In the Race Round, the top 16 shortlisted racers compete with each other to win the Race King title.",
                "The 16 players are split into groups of 4 racers each. Two racers are shortlisted from each group after the race. They are then forwarded to the next round.",
                "There are 3 rounds in total for the Race Round.",
                "Players of each round will be asked if they prefer to have car collision on or off.",
            ],
            reg_fees: "30",
            posterImg: SpeedFreak,
            coordinator: ["Arnold Denzil", "Abhiram A", "Shajith Joseph"],
            contact_coordinator: ["8078339113", "8089618237", "9539147591"],
        },
        {
            id: 3,
            title: "CYBERVERSE – VR GAMING",
            first_price: "1500",
            second_price: "",
            prizeCount: 1,
            third_price: "",
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "10:00 AM - 4:00 PM",
            desc: "Virtual reality (VR) is a simulated experience that employs pose tracking and 3D near-eye displays to give the user an immersive feel of a virtual world",
            rules: [
                "The event is open to all students who are passionate about VR Gaming.",
                "The event will span for the whole day. ",
                "The grand winner will be decided by the player who sets the highest score.",
                "Participants must follow all instructions given by the organizers.",
                "The decision of the coordinators will be final and binding.",
            ],
            reg_fees: "30",
            posterImg: cyberverse,
            coordinator: ["Jubin Thomas", "Muhammed Firoz", "Abhijith C A"],
            contact_coordinator: ["9061313287", "9496436031", "7012904254"],
        },
        {
            id: 4,
            title: "FILM TRIVIA – FILM QUIZ",
            first_price: "1500",
            second_price: "1000",
            third_price: "",
            prizeCount: 2,
            type: "Team(2 Members)",
            mode: "Offline",
            date: "19",
            time: "9:00 AM - 12:00 PM",
            desc: "Lights, camera, laughter!\nGet ready to put your film knowledge to the test with Film Trivia, the ultimate game for movie buffs.",
            rules: [
                "Maximum of 2 participants are allowed in a team.",
                "The team should be present at the time. Those who are late will be not allowed to play the game. ",
                "All teams should be present at least 5 minutes prior to the event.",
                "Malpractices are not allowed, if found will lead to the termination of entire team.",
                "Only English and Malayalam movies will be asked for the game.",
                "Decisions of judges will be final regarding all the matters of the game."
            ],
            reg_fees: "50",
            posterImg: Filmtivia,
            coordinator: ["Karthik H", "Parvathy S", "Anjana", "Vandana Unni"],
            contact_coordinator: ["8547351305", "7306862790 ", "8129145896", "9656095813"],
        },
        {
            id: 5,
            title: "HACKATHON",
            first_price: "4000",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Team(2 Members)",
            mode: "Offline",
            date: "19",
            time: "9:00 AM - 12:00 PM",
            desc: "Ready to unleash your creative beast and slay some problems? Join our Hackathon and become a problem-solving ninja!\nWhether you're a coding whiz, a UX/UI mastermind, or just someone with a passion for innovation, this Hackathon is your chance to shine!",
            rules: [
                "Each team will consist of two participants.",
                "The teams will receive the theme for the hackathon by registered mail.",
                "Every team is required to submit their ideas before the hackathon starts.",
                "The submission must include a short description of the idea, the cost, and any resources or tools required to develop it.",
                "Each team is given 5 minutes to present their idea to the judges and the audience.",
                "The presentation should include a clear description of the problem being solved, how the idea solves the problem, and any unique features or benefits of the idea.",
            ],
            reg_fees: "100",
            posterImg: Hackathon,
            coordinator: ["Arya", "Vaishnavi", "Anand", "Devaprasad"],
            contact_coordinator: ["8547589132", "9778248972", "7306264750", "8086567429"],
        },
        {
            id: 6,
            title: "SPIDERZ-WEB DEVELOPER COMPETITION",
            first_price: "3000",
            second_price: "1000",
            third_price: "",
            prizeCount: 2,
            type: "Individual",
            mode: "Online & Offline",
            date: "19 & 20",
            time: "9:00 AM Onwards",
            desc: "Online (First Round)- 18th Apr 7.00PM to 19th Apr 7.00PM\nOffline (Second Round) - 20th Apr 1.00PM to 20th Apr 4.00PM",
            rules: [
                "Competition will have 2 levels.",
                "In the primary round, a topic will be given to the participants on 18thApril 7.00PM, they can research about the topics in internet.",
                "The participant can take resources from the internet and design an attractive webpage.",
                "There is 24hrs time and they should submit webpage on 19th April 7.00PM.",
                "Late submission is not allowed.",
                "15% participants who are shortlisted from the first level can participate in the second level (20th April 12.00PM - 03.00PM 3Hrs).",
                "Topic will be given on the starting time only. In this level participants can use the resources from internet like videos and photos they can't take any code from the internet, the usage of AI application Strictly prohibited.",
                "Use of mobile phones are not allowed.",
            ],
            reg_fees: "20",
            posterImg: Spiderz,
            coordinator: ["Adithyan S Pillai", "Neeraj J", "Sreelekshmi"],
            contact_coordinator: ["9605987219", "8281307620", "8129374881"],
        },
        {
            id: 7,
            title: "TECH WIZARD",
            first_price: "3000",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Individual",
            mode: "Online & Offline",
            date: "20",
            time: "10:00AM Onwards",
            desc: "All the you computer nerds out there, take note. Are you prepared to show your worth? Prepare to participate in the pinnacle of technical competitions. Avail this golden opportunity and be the TECH WIZZZAARD",
            rules: [
                "Participation is open to all. ",
                "Spot registrations are available but limited. ",
                "Decision of the coordinators are final. ",
                "Malpractices are not allowed.",
                "Participants are requested to arrive on time. ",
                "The competition consists of 3 rounds-",
                "Debugging, Blind Coding & PC assembly"
            ],
            reg_fees: "100",
            posterImg: TechWizard,
            coordinator: ["Adithya Vijayan", "Athira Ajikumar B", "Amith Vinod", "Anandu R", "Kailas Krishna"],
            contact_coordinator: ["7736897590", "7736897590", "6282535641", "6282535641", "8075653841"],
        },
        {
            id: 8,
            title: "WEBZEIGN-UI DESIGNING",
            first_price: "1250",
            second_price: "750",
            prizeCount: 2,
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "11:00 AM – 12:45 PM",
            desc: "WEBZEIGN challenges designers to create visually appealing and user-friendly interfaces for a given topic. Participants are judged on their creativity, functionality, and overall user experience.",
            rules: [
                "WEBZEIGN will be a designing of a mobile application UI , The topic will be given at the time of competition ",
                "Designing tool will be Figma. Workspace will be allotted for each participant by their name",
                "A person has 2 hrs to complete the design, minimum 4 frame required",
            ],
            reg_fees: "20",
            posterImg: webizign,
            coordinator: ["Harikrishnan", "Mathew George", "Sreejith"],
            contact_coordinator: ["9995280526", "9947830781", "8137006907"],
        },
        {
            id: 9,
            title: "CODE MAFIA – RELAY CODING",
            first_price: "3000",
            second_price: "1000",
            third_price: "",
            prizeCount: 2,
            type: "Team(3 Members)",
            mode: "Offline",
            date: "20",
            time: "11:00 AM – 12:45 PM",
            desc: "Programmers showcase your programming skills in C and compete to solve a set of challenges in a limited amount of time and wiz exciting prize.",
            rules: [
                "The team should decide the order of players for competing in the particular round.",
                "Each player will have three minutes of time to solve the problem.",
                "After three minutes, the next player can start solving the remaining problem.",
                "The no of rounds will be decided based on the no of participants",
            ],
            reg_fees: "0",
            posterImg: CodeMafia,
            coordinator: ["A.L Hari Shekhar", "Antony K Mathew", "Aravind Suresh0", "M. Raoof"],
            contact_coordinator: ["9847870656", "7356304231", "7902330867", "9995459326"],
        },
        {
            id: 10,
            title: "PATTERN PRINTING",
            first_price: "3000",
            second_price: "1000",
            third_price: "",
            prizeCount: 2,
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "2:00 PM – 4:00 PM",
            desc: "Think you're a pattern printing pro in C? Compete with other coding enthusiasts to see who can generate the most accurate pattern that we provide! Put your skills to the test and showcase your creativity while having fun.",
            rules: [
                "To confirm their eligibility, participants must present a current college ID card to the event.",
                "Each contender is only permitted one entry.",
                "Participants must make sure their answers are comprehensive and submitted correctly before the given time runs out in order to be evaluated.",
                "The location must be reached by the participants on time.",
                "Only the PCs provided by the organizers should be used by participants.",
                "Participants are urged to concentrate on coming up with ideas as quickly and precisely as possible because speed will play a role in determining the winner.",
                "The winners will be the only ones to receive the rewards, which cannot be transferred to anyone else.",
                "Any rule infractions or any misbehaviour will result in exclusion from the competition, and the judges' judgement is final.",
            ],
            reg_fees: "20",
            posterImg: Patternprinting,
            coordinator: ["Ebin Varghese", "Abishek"],
            contact_coordinator: ["7558844341", "7907247909"],
        },
        {
            id: 11,
            title: "HYPER LINK ",
            first_price: "1500",
            second_price: "500",
            third_price: "",
            prizeCount: 2,
            type: "Individual",
            mode: "Offline",
            date: "20",
            time: "10:00 AM – 12:30 PM",
            desc: "All of us have been there looking at links for clues as to what the page is about and where to go next for our needs.\nIn this competition, we will give you a source word and all that you need to do is click, click and click on the incoming links to reach the word at the destination.",
            rules: [
                "There will be 3 levels for the competition ",
                "Two participants cannot share the same system.",
                "The fastest participant to reach the keyword wins.",
                "Malpractices will result in Disqualification.",
                "The decisions of Judges will be final regarding all the matters of the event.",
                "Use of 'CTRL+F' and other shortcut keys are strictly prohibited",
            ],
            reg_fees: "30",
            posterImg: Hyperlink,
            coordinator: ["Ansu Varghese", "Aswin S Seshadri", "Abhiram Venugopal"],
            contact_coordinator: ["9605443353", "6238088681", "8304020968"],
        },
        {
            id: 12,
            title: "PLAY PLEX – GAMING ROOM",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            prizeCount: 0,
            mode: "",
            date: "",
            time: "",
            desc: "Play For Fun, Not for Prize\nExperience the Reality in Ultimate gaming\nThe anticipation comes to an end!!!!\nAre you a hardcore gamer looking for a fun and engaging way to connect with other like-minded gamers? Look no further than our upcoming gaming room event! Join with us for non-stop gaming action, socializing, and friendly competition...10+ Games with highly modified gaming equipment's have worth up to 1 million.\nEntry fees\n20/- (for 15 minutes/per game)\n50/- (for 30 minutes/Any games)\nSo mark your calendar, invite your friends, and get ready to level up at our gaming room event.",
            rules: [
                "Equipment care: Treat gaming equipment with care and report any malfunctions or damage to the volunteers. Do not tamper with or modify the equipment in any way, if any malfunctioning in device happens, it will result you to pay fine of the device amount!!!",
                "Time limits: Time limits may be imposed to ensure that all players have a chance to use the gaming room. Players should be considerate of others and avoid monopolizing the equipment or facilities.",
                "Volunteers instructions: Players should follow any instructions or requests from the volunteers of the gaming room. Failing to comply with rules or volunteers’ instructions may result in suspension or revocation of gaming room privileges.",
            ],
            reg_fees: "20",
            posterImg: Playplex,
            coordinator: ["Justin James", "Rahul Mane", "Karthik"],
            contact_coordinator: ["8075512624", "9061630557", "9567443356"],
        },


    ],

    civil: [
        {
            id: 1,
            title: "RAPID WALL",
            first_price: "3000",
            second_price: "1500",
            third_price: "",
            prizeCount: 2,
            type: "Team(3 Members)",
            mode: "Venue(MT Lab)",
            date: "19 April 2023",
            time: "10:00 AM - 12:00 PM",
            desc: "The competition is to unveil talent of your team as a bricklayer. Build the bricks perfectly in the stipulated time and you will be the winner.",
            rules: [
                "Time limit – 2 hours; late admissions are not allowed",
                "No refunds.",
                "Decisions of the judges are final.",
                "Use the provided materials only.",
                "The organizers are not responsible for the safety of contestants.",
                "Violation of the above rules leads to disqualification of the team.",
            ],
            reg_fees: "100 Per Person",
            posterImg: "",
            coordinator: ["Enosh ","Vinaya  "],
            contact_coordinator: ["7012288973","9446286673"],
            gform:"https://docs.google.com/forms/d/1n0hO5qyuRL23rj7UUsahceys6cxPn3bSNoRQfBkzzXs/edit"
        },
        
        {
            id: 2,
            title: "THE BEST SURVEYOR",
            first_price: "4000",
            second_price: "2000",
            third_price: "",
            prizeCount: 2,
            type: "Team(4 Members)",
            mode: "Venue(SURVEY Lab)",
            date: "20 April 2023",
            time: "10:00 AM - 1:00 PM",
            desc: "Here it is, THE BEST SURVEYOR, where you can exhibit your top notch-skills in surveying. Techniques are all that matters in here, so bring it up.",
            rules: [
                "The participants should have the college ID card with them.",
                "Participation will be allowed only after prior registration.",
                "In this competition, the competitors will have to use surveying equipment's such as chain, tape, dumpy level and theodolite.",
                "Duration for the competition is 3 hours.",
                "Equipment's will be provided.",
        
            ],
            reg_fees: "50 Per Person",
            posterImg: "",
            coordinator: ["Emmanuel Jerome ","Enosh"],
            contact_coordinator: ["8078852891","7012288973"],
            gform:"https://docs.google.com/forms/d/1yk9Bg3y3fj_0a2-hGct7L32_xBkjXtY5N5RvRgYSB1c/edit"
        },

        {
            id: 3,
            title: "MIX AND CAST",
            first_price: "3000",
            second_price: "1500",
            third_price: "",
            prizeCount: 2,
            type: "Team(3 Members)",
            mode: "Venue(MT Lab)",
            date: "20 April 2023",
            time: "1:00 PM - 3:00 PM",
            desc: "Its time to enhance and show your interest on concrete mix design. We present you mix design workshop and mix design competition with exciting prices.",
            rules: [
                "DESIGN BASED ON IS 10262.",
                "TIME LIMIT 30 MINUTES",
                "7 DAYS COMPRESSIVE STRENGTH.",
                "MARK DISTRIBUTION :",
                "Relevant calculation-30%",
                "Accuracy of strength-50%",
                "Timing-20%",
                ],
            reg_fees: "100 Per Person",
            posterImg: "",
            coordinator: ["Abin","Bichu"],
            contact_coordinator: ["9446387700"," 8943440168"],
            gform:"https://docs.google.com/forms/d/1MJHmqHQHgMe5yQ2EH_cmc0-EHo6BG7qFp4qY_fX3s5c/viewform?edit_requested=true"
        },

        {
            id: 4,
            title: "SOAPY SOCCER",
            first_price: "3000",
            second_price: "1500",
            third_price: "",
            prizeCount: 2,
            type: "Team(3 Members)",
            mode: "Venue(Near Library)",
            date: "19 April 2023",
            time: "10:00 PM - 4:30 PM",
            desc: "Two teams each of 3 will face off in a football match on an inflated court with slippery floor. A great way to pass the time for both casual and hardcore soccer enthusiasts.",
            rules: [
                "Number of players will be 3 with 1 substitute.",
                "Nylon T-shirts and shorts are compulsory.",
                "Match will be of 10 minutes.",
                "Decision of the referee will be final.",
                ],
            reg_fees: "100 Per Person",
            posterImg: "",
            coordinator: ["Arif","Anandhan"],
            contact_coordinator: ["7736192192"," 9746577837"],
            gform:"https://docs.google.com/forms/d/e/1FAIpQLSdUxg7B0qHEP81Aue57VO-Fwt8545IVKL6Ns1rMWsbF21MHoQ/viewform"
        },
       
        {
            id: 5,
            title: "FACE TO FACE ",
            first_price: "2000",
            second_price: "1000",
            third_price: "",
            prizeCount: 2,
            type: "Team(2 Members)",
            mode: "Venue(S7/S8 CIVIL)",
            date: "20 April 2023",
            time: "10:00 PM - 2:00 PM",
            desc: "An event where you can explore the Vincent van Gogh in you.  Face to face is a competition of painting on your friend’s face and unlock your creative skills.",
            rules: [
                "Participants will be provided with Acrylic paint and brushes.",
                "Time limit - 2 hours.",
                "Topic will be given on the spot.",
                "Participants will be judged on the basis of creativity, innovation, design and completion of the work.",
                ],
            reg_fees: "100 Per Person",
            posterImg: "",
            coordinator: ["Anjali","Arya"],
            contact_coordinator: ["7902507796"," 7034814836"],
        },
       
        {
            id: 6,
            title: "CLASH OF CADD",
            first_price: "3000",
            second_price: "1500",
            third_price: "",
            prizeCount: 2,
            type: "Team(2 Members)",
            mode: "Venue(CIVIL LAB)",
            date: "19 April 2023",
            time: "9:30 PM - 12:30 PM",
            desc: "This event demonstrates mastery in AutoCAD skills. Sparks 2k23 presents clash of CADD, a competition of designing residential building with unique ways.",
            rules: [
                "Ensure your entry through registration on or before 17-04-2023.",
                "Time limit is 2.5 hr.",
                "ID card is mandatory.",
                "Participants will be provided with pencil, rubber and scribbling pad.",
                "Students should complete the plan, elevation and section within the time limit.",
                "Incomplete drawings will be rejected.",
                "Titleblock, proper indications, dimensions are mandatory.",
                "The drawings should be submitted in PDF format.",
                ],
            reg_fees: "100 Per Person",
            posterImg: "",
            coordinator: ["Nadiya","Revathy"],
            contact_coordinator: ["9446284019","7559908255"],
        },

        {
            id: 7,
            title: "MINUTE TO WIN IT",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "Individual",
            mode: "Venue(NEAR LIBRARY)",
            date: "19 April 2023",
            time: "10:00 PM - 4:00 PM",
            desc: "What can you do in 60 seconds?\nIf you can complete a number of tasks which require basic skillset within one minute, then you can take home some real money.\nPrize\n₹50 on successful completion of 5 rounds\n₹100 on successful completion of 10 rounds\n₹200 on successful completion of 15 rounds",
            rules: [
                "The game will be of 3 rounds each with 5 levels.",
                "Successful completion of each round will guarantee cash prizes.",
                "Contestants should complete the task within the 60 seconds.",
                "​Contestants should clear all the queries about the task before commencing of the level.",
                "The decision of the event organizers will be final.",
                ],
            reg_fees: "50 Per Person",
            posterImg: "",
            coordinator: ["Amal","Goutham"],
            contact_coordinator: ["8137831701","9446683865"],
        },

        {
            id: 8,
            title: "ESCAPE ROOM",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "Team(3 Members)",
            mode: "Venue(NEAR LIBRARY)",
            date: "19,20 April 2023",
            time: "10:00 PM - 4:00 PM",
            desc: "Are you up for the challenge? Can you escape the dreadful room? Have a blast solving puzzles and tricks with your buddies and escape the room which has some hidden surprises.",
            rules: [
                "All phones need to be left outside the room.",
                "You are not locked in. If you need to leave at any time, you can come out the door you came in.",
                "You have 15 minutes to escape.",
                "What you hear or see, leave here; do not share any puzzles, hints or clues. Share the fun, but don’t spoil the fun for others!",
                "If you ruin a clue, there will be no way to finish the escape",
                ],
            reg_fees: "50 Per Person",
            posterImg: "",
            coordinator: ["Victor","Dilsha"],
            contact_coordinator: ["8301838768","7306913966"],
        },

        {
            id: 9,
            title: "MYSTERIO(TREASURE HUNT)",
            first_price: "3500",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Team(4 Members)",
            mode: "Venue(S3/S4 CIVIL)",
            date: "19,20 April 2023",
            time: "10:00 PM - 4:00 PM",
            desc: "The Hunt is on! Are you ready???\nThis is Mysterio (The Treasure Hunt) presenting civil engineering association as part of Sparkz 2k23.\nEnsure your entry through registration. Come on the Treasure is waiting for you!!",
            rules: [
                "Ensure your entry through Registration on or before 14 April 2023.",
                "Use of mobile phone is prohibited.",
                "Copying from other teams is not allowed.",
                "Interfering with other teams is not allowed.",
                "Teams must stay together during the Treasure Hunt.",
                "Violation of the above rules and regulations leads to the qualification of the team.",
                ],
            reg_fees: "200",
            posterImg: "",
            coordinator: ["Harsha","Gayathri"],
            contact_coordinator: ["7306395212","6282534843"],
            gform:"https://docs.google.com/forms/d/e/1FAIpQLSf5rIfds540fh2kL5VNJqxfukBB63pSCkkWwFqfXOl8lcLBDg/viewform?vc=0&c=0&w=1&flr=0"
        },

        {
            id: 10,
            title: "GRADITI 23",
            first_price: "EXHIBITION EVENT",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "INDIVIDUAL",
            mode: "Venue(CIVIL pavilion)",
            date: "19,20 April 2023",
            time: "9:00 PM - 4:00 PM",
            desc: "GRADITI 23",
            rules: [
               
                ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["Elias Thomas Kalloor (Assistant Professor)","Jayakrishnan P.B(Assistant Professor)"],
            contact_coordinator: ["8281350803","8281230257"],
        },
        
    ],

    mech: [
        {
            id: 1,
            title: "ITBP WEAPON SHOW",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "Individual",
            mode: "VENUE ()",
            date: "19",
            time: "10:00AM - 12:00 PM",
            desc: "The exhibition intended to raise knowledge of the many types of armaments used in the Army, as well as to inspire young people to pursue careers in the armed forces. Students were taught about line display ammunition, and how to handle weapons in an actual combat scenario. SPARKZ 2K23 is provided as a platform to explore it.",
            rules: [
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["Akshay Kumar","Ashish Kumar"],
            contact_coordinator: ["7306405353","8310485153"],
        },
        {
            id: 2,
            title: "LATHE MASTER",
            first_price: "2000",
            second_price: "1500 ",
            third_price: "1000",
            prizeCount: 3,
            type: "Team[2 MEMBERS]",
            mode: "VENUE ()",
            date: "19",
            time: "10:00AM - 12:00 PM",
            desc: "This is it, an event where you can show how strong you are in virtual workshop practices. Lathe Master is a competition of producing a mechanical component given in drawing by using a lathe machine.",
            rules: [
                "If any damage to tool, lathe m/c, surrounding etc, or any malpractices including negligence during machining will lead to disqualification.",
                "Fine will be taken if any major damages to Tool, Lathe Machine or Surroundings occur during Operation.",
                "After the completion of the task all the accessories must be returned.",
                "No extra work piece will be provided and carrying of any extra material is banned.",
                "Judge’s decision will be final, binding to all and irrevocable.",
                "Participant is responsible for their own safety",
                "They should Compulsory have apron and shoes",
                "IF THE PARTICIPATION IS MINIMUM CASH PRICE WILL NOT BE AWARDED.",
            ],
            reg_fees: "50",
            posterImg: "",
            coordinator: ["Abdullah A M","Anjana Baby"],
            contact_coordinator: ["8281164581","9778596121"],
        },
        {
            id: 3,
            title: "CAD MASTER",
            first_price: "2000",
            second_price: "1500",
            third_price: "1000",
            prizeCount: 3,
            type: "INDIVIDUAL",
            mode: "VENUE ()",
            date: "19",
            time: "10:00AM - 12:00 PM",
            desc: "To test the speed, analytical thinking along with the creativity of the participant Sparkz 2K23 presents CAD MASTER.",
            rules: [
                "The contest is open to the undergraduate students of all engineering colleges in Kerala.",
                "The judgement will be based on the accuracy.",
                "The decision of the Judging Committee in this regard shall be final.",
                "Assembly drawing through SOLID EDGE (1.5 hours).",
                "iF THE PARTICIPATION IS MINIMUM CASH PRICE WILL NOT BE AWARDED",
            ],
            reg_fees: "50",
            posterImg: "",
            coordinator: ["Adarsh R","Gourinath"],
            contact_coordinator: ["9072985323","9947084250"],
        },
        {
            id: 4,
            title: "PROJECT PRESENTATION",
            first_price: "2000",
            second_price: "1500",
            third_price: "1000",
            prizeCount: 3,
            type: "INDIVIDUAL",
            mode: "VENUE ()",
            date: "19",
            time: "10:00AM - 12:00 PM",
            desc: "SPARKZ 2K23 is provided as a platform for future engineers to showcase their innovative projects which could solve real time problems based on the given set of themes. By participating in SPARKZ 2K23, you will be able to make your technical experience much more. Why waiting? Grab your laptops and a cup of coffee and register now.",
            rules: [
                "The decision of the Judging Committee in this regard shall be final.",
                "It should be completely related with Mechanical Engineering.",
                "IF THE PARTICIPATION IS MINIMUM CASH PRICE WILL NOT BE AWARDED.",
            ],
            reg_fees: "50",
            posterImg: "",
            coordinator: ["Yadu Anilkumar","Sruthy"],
            contact_coordinator: ["9846110932","9645964869"],
        },
        {
            id: 5,
            title: "BRAIN CYCLE",
            first_price: "2000",
            second_price: "1500",
            third_price: "1000",
            prizeCount: 3,
            type: "INDIVIDUAL",
            mode: "VENUE() ",
            date: "19",
            time: "",
            desc: "",
            rules: [
                "Distance should be 15 meters (Time to cover is allocated only at the event).",
                "The decision of the Judging Committee in this regard shall be final.",
                "iF THE PARTICIPATION IS MINIMUM CASH PRICE WILL NOT BE AWARDED.",
            ],
            reg_fees: "50",
            posterImg: "",
            coordinator: ["Abhijith S","Faslu"],
            contact_coordinator: ["7902260566","9633222083"],
        },
        {
            id: 6,
            title: "GO KART",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "INDIVIDUAL",
            mode: "VENUE ()",
            date: "19,20",
            time: "10:00AM - 12:00 PM",
            desc: "Karting is a road racing variant of motorsport with open wheel, four-wheeled vehicles known Go karts. They are usually raced on scaled-down circuits, although some professional kart races are also held on full-size motorsport circuits. By participating you will be able to experience the Go-kart Racing\nThe entry tickets and the lap is on the following basis:\n1 Lap - ₹50\n2 Lap - ₹100\n4 Lap - ₹200\n8 Lap - ₹300",
            rules: [
                "Safety of students is our first priority!",
                "You are responsible to obey the track marshals, their signals, flags and rules.",
                "All Drivers must obey Rules and Regulations",
                "Keep hands and feet inside go-kart.",
                "Must ensure your belongings. The coordinators will not be responsible if its lost while driving.",
                "Use Brakes before turns.",
                "Avoid contact with the side wall and ensure yours and others safety.",
                "If the kart hits on the side wall more than 3 times, you will be disqualified and you will not be permitted to drive more.",
                "If you break the rules, there will be no refund and needs to stop driving and follow coordinators instructions.",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["Athuljith","Lemin"],
            contact_coordinator: ["8138842688","6282727638"],
        },
        {
            id: 7,
            title: "ENGINE EXHIBITION",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "Individual",
            mode: "VENUE (TE LAB)",
            date: "19,20 April 2023",
            time: " 10:00AM - 12:00 PM",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["Jackson Scaria","Darshan A Mathew", ""],
            contact_coordinator: ["8281254781","8157024882"],
        },
        {
            id: 8,
            title: "CAR DISMANTLING ",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "Individual",
            mode: "VENUE()",
            date: "19,20 April 2023",
            time: "10:00AM - 12:00 PM",
            desc: "To move towards a more sustainable and circular economy, a more efficient recovery processes for end-of-life vehicles and their constituent components and materials is needed. To enable reuse, remanufacturing, high-value recycling and other circular strategies, a well-functioning disassembly is arranged in SPARKZ 2K23 .",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["Asif N","Jithin John Thomas", "Ananthakrishnan C"],
            contact_coordinator: ["8547432951","9567044073","7356277608"],
        },
        {
            id: 9,
            title: "CONTRAPTION",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "Individual",
            mode: "VENUE (S7/S8 MECH)",
            date: "19,20 April 2023",
            time: " 10:00AM - 12:00 PM",
            desc: "To move towards a more sustainable and circular economy, a more efficient recovery processes for end-of-life vehicles and their constituent components and materials is needed. To enable reuse, remanufacturing, high-value recycling and other circular strategies, a well-functioning disassembly is arranged in SPARKZ 2K23 .",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["Adharsh Sebastian","Gautham U"],
            contact_coordinator: ["9567501248","7994180934"],
        },
    ],

    electrical: [
        {
            id: 1,
            title: "RC RACING",
            first_price: "Prize Worth 3000",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Team(2 Members)",
            mode: "Venue()",
            date: "19,20 April 2023 ",
            time: "",
            desc: "Can you survive on this perilous path and succeed?",
            rules: [
                "The RC cars will be provided from the college itself.",
                "Participant who complete the lap with in the shortest time will be the winner",
                "The RC car must travel through different terrains and additionally the track would contain obstacles to make the contest more challenging.",
                "winners will be decided on the least amount of time taken to complete the terrain.",
                "The participants may not touch the RC Car while it is on the course. Only on the supervision of the officials, the participants are allowed to reset the Car at the checkpoints if necessary. Any violation of this rule may lead to disqualification.",
                "Decision of the judging committee will be final and there is no scope for appeal.",
                "Certificate issued can earn the participants KTU activity points.",
            ],
            reg_fees: "50",
            posterImg: "",
            coordinator: ["Akshay S","Antony Sebastian"],
            contact_coordinator: ["9633053776","9020802059"],
        },

        {
            id: 2,
            title: "ROBOTRIX",
            first_price: "Prize Worth 3000",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Team(3 Members)",
            mode: "Venue()",
            date: "19 April 2023 ",
            time: "",
            desc: "Participants will have to make their robot run in a given line path using Arduino application within the given time limit.",
            rules: [
                "A minimum of 10 teams are mandatory for determination of winners. ",
                "Maximum no of participants in a team is 3.",
                "Laptop will be provided for programming purpose. ",
                "20 minutes will be given in total. ",
                "Any robot that goes out of course line will be treated as lost attempt.",
                "Maintain discipline throughout the program.",
                "Any Student ID card is mandatory.",
                "Judges decision will be final.",
                "Certificate issued can earn the participants KTU activity points.",
            ],
            reg_fees: "50",
            posterImg: "",
            coordinator: ["Akshay Krishnan","Varghese Mathew"],
            contact_coordinator: ["8138953027","8086118753"],
        },

        {
            id: 3,
            title: "SIMULINK MODELLING",
            first_price: "Prize Worth 3000",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Individual",
            mode: "Venue()",
            date: "19,20 April 2023 ",
            time: "",
            desc: "The participants have to design the given system using simulink tool available in MATLAB and obtain the proper output.",
            rules: [
                "Only individual participation is allowed.",
                "Max. time allotted for the completion of task is 20 minutes.",
                "No extra time beyond the time limit will be permitted.",
                "PC with MATLAB is provided within the campus. • No electronic devices are permitted inside the lab. [Laptop, smartphone, smart watch, pen drive, etc.. ]",
                "Instructions regarding the task will be given to the participants before the commencement of the task.",
                "Malpractice will lead to disqualification.",
                "Decision of judges are final in all respects.",
                "Submission of all entries to the competition implies acceptance of the above rules.",
                "Certificate issued can earn the participants KTU activity points.",
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Neeraja Maria Noel","Aswini Amruthakumar"],
            contact_coordinator: ["9497301257"," 9497359474"],
        },

        {
            id: 4,
            title: "CIRCUIT DEBUGGING",
            first_price: "Prize Worth 1500",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Team(2 Members)",
            mode: "Venue()",
            date: "19,20 April 2023 ",
            time: "",
            desc: "Participants has to troubleshoot the bug in the given circuit and obtain the required output successfully within the time limit",
            rules: [
                "There should be at least 15 participants for the event.",
                "Use of smart electronic devices is strictly prohibited.",
                "There will be a screening round.",
                "Participants who clear the screening round will qualify for the final were the winners will be decided on the amount of time taken.",
                "Decision of the judging committee will be final and there is no scope for appeal.",
                "Certificate issued can earn the participants KTU activity points.",
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Abhinav Rajesh","Haripriya L"],
            contact_coordinator: ["9633513721","6282046416"],
        },

        {
            id: 5,
            title: "CIRCUITRIX",
            first_price: "Prize Worth 1500",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Individual",
            mode: "Venue()",
            date: "19 April 2023 ",
            time: "",
            desc: "In this participants knowledge on the basis of electronics and build a base in this field will be tested.",
            rules: [
                "Competition will be conducted individually.",
                "There should be at least 15 participants for the event.",
                "Using of smart electronic devices is strictly prohibited.",
                "Problem statement will be provided at the venue.",
                "There will be a screening round.",
                "Focus on the circuit implementation abilities of the participants.",
                "Participants will be provided with components of circuit on demand.",
                "They have to implement the physical circuit and generate required output.",
                "There will be stage wise evaluation.",
                "Decision of judging committee will be final and there is no scope for appeal.",
                "Certificate issued can earn the participants KTU activity points.",
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Jobina Jose","Amaljith.P"],
            contact_coordinator: ["9778075439","7736180898"],

        },

        {
            id: 6,
            title: "MOBILE PHOTOGRAPHY",
            first_price: "Prize Worth 1500",
            second_price: "",
            third_price: "",
            prizeCount: 1,
            type: "Individual",
            mode: "Venue()",
            date: "19,20 April 2023 ",
            time: "Submit before 20 April",
            desc: "Can you survive on this perilous path and succeed?",
            rules: [
                "Participants are required to provide a unique title and description for each image submitted.",
                "Image specifications o Image should not exceed 25MB o Image format: jpg, jpeg.",
                "Image taken using mobile phone cameras only will be accepted. ",
                "All pictures should be original. Cropping /correction of brightness, contrast, sharpness, white balance to enhance the quality are not permitted.",
                "Entries with watermark/individual name will not be accepted.",
                "The decision of the judges will be final in all respects.",
                "Submission of the entries to the competition implies acceptance of the above rules",
                "In case of any disputes organizers decision will be final. ",
                "Images for mobile photography should be uploaded to the mail ID mentioned below: sparkz23eee@gmail.com",
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Amal Shaji","Firoz Mujeeb"],
            contact_coordinator: ["8848667161","8590194316"],
        },

        {
            id: 8,
            title: "TECHNICAL EXPO",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "",
            mode: "",
            date: "19,20 April 2023 ",
            time: "",
            desc: "",
            rules: [
                
                            ],
            reg_fees: "",
            posterImg: "",
            coordinator: [""],
            contact_coordinator: [""],
        },
    ],

    basic_science: [
        {
            id: 1,
            title: "A Glimpse to KEAM- MOCK test for KEAM aspirants",
            first_price: "",
            second_price: "",
            third_price: "",
            prizeCount: 0,
            type: "OFFLINE EXAM",
            mode: "VENUE (2ND FLOOR)",
            date: "19",
            time: "",
            desc: "Basic Science department of Carmel college of engineering conducts a mock test for KEAM 2023 in association with SPARKZ 23.",
            rules: [
                "KEAM aspirants can register for this free MOCK test which will be conducted in offline mode on 19th April 2023 at Carmel College of Engineering and Technology, Punnapra,Alappuzha.The Exam will start at 10 AM and participants should report the centre at 9.30 AM.",
                "Registration link is provided in this website. Interested candidate may also register by contacting the faculty.",
                "Syllabus for the exam will be same as that of KEAM 2023.",
                "The exam will be of 3 Hour duration.",
                "There will be a total of 120 questions. Subject wise division of questions is as follows\nPhysics- 30 questions\nChemistry- 30 Questions\nMathematics – 60 Questions",
                "Exam will be conducted in offline mode using OMR sheets. Use black or blue ball point pen for filling the OMR sheet.",
                "Calculators or any other electronic devices are not allowed in examination hall.",
                "4 marks will be awarded for every correct answer 1 mark will be deducted for an incorrect answer",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["ROOPAK","KARTHIKA", "MARTIN"],
            contact_coordinator: ["9562930614","9567661646","9567282100"],
        },
        {
            id: 2,
            title: "BRAIN BATTLE- Inter School Quiz Competition",
            first_price: "5000",
            second_price: "3000",
            third_price: "2000",
            prizeCount: 3,
            type: "TEAM (2 MEMBERS)",
            mode: "VENUE (2nd FLOOR)",
            date: "20",
            time: "9:00 AM",
            desc: "Basic Science and Humanities department of Carmel college of engineering organizes an a Inter School Quiz Competition in association with SPARKZ 23. The competition will be hosted by Kerala Sasthra Sahithya Parishadh.",
            rules: [
                "The participants shall be from class VIII to XII. This is a team event and a team of two students can participate in this quiz.",
                "Registration link is provided in this website. Interested candidate may also register by contacting the faculty.",
                "There will be no registration fees and there is no restriction for number of teams from a   school.",
                "Questions will be based on Science and Technology and General Knowledge.",
                "The quiz will consist of different levels and rounds. Participants may bring mobile phones (If available). Some rounds may need the use of Mobile phones. If Mobile phones are not available, organizers will provide it for such rounds.",
                "There will be an elimination round if the number of applications is large.",
                "The decision of Quiz Masters shall be final and binding on the participants.",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["ROOPAK","KARTHIKA", "MARTIN"],
            contact_coordinator: ["9562930614","9567661646","9567282100"],
        },
        {
            id: 3,
            title: "Science Safari – Working model Exhibition Competition",
            first_price: "5000",
            second_price: "3000",
            third_price: "2000",
            prizeCount: 3,
            type: "TEAM(5 MEMBERS)",
            mode: "VENUE (2ND FLOOR)",
            date: "20",
            time: "1:30 PM",
            desc: "This working model exhibition is intended to explore and encourage scientific and technological talent and creative thinking among children and inculcate in them a sense of pride in their talent.",
            rules: [
                "The participants shall be from class VIII to XII. They can participate individually or in a group of maximum 5 students.",
                "There will be no registration fees and there is no restriction for number of teams from a school.",
                "Participants can register either via the link provided in this website or contacting the faculty directly. Spot registration is also available.",
                "There is no common theme for exhibition. Participants can choose their own theme for working model.",
                "Evaluation of the working model will be based on the following. \nCreative imagination.\nScientific thought and approach.\nOriginality and innovations in the model.\nTechnical skill (Art &Craftsmanship)\nEconomic (low cost/portability/durability)\nPresentation (demonstration & explanation)",
                "The decision of Judges shall be final and binding on the participants."
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["ROOPAK","KARTHIKA", "MARTIN"],
            contact_coordinator: ["9562930614","9567661646","9567282100"],
        },
    ]
}

export default events